services:
  api:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - yard-gem-index:/home/ruby/.yard/gem_index
      - bashlog:/home/ruby/bashlog
      - vscode-extensions:/home/ruby/.vscode-server/extensions
    command: bash -c "while sleep 1000; do :; done"
volumes:
  yard-gem-index:
  bashlog:
  vscode-extensions:
